# This workflow will upload a Python Package using Twine when a release is created.
# For more information see: 
# * https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries
# * https://github.com/pypa/gh-action-pypi-publish

name: Build and Publish Python Package

on:
  release:
    types: [published]
    #types: [created]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        cache: 'pip'
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
    - name: Build package
      run: |
        python -m build
     
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
